#concatenar vectores o matrices

np.concatenate((a1, a2, ...), axis=0)

 - a1,a2,...: son vectores o matrices de NumPy
 - axis: eje a lo largo del cual se desea que se concatenen los vectores o matrices. Valores:
      - 0 : une por filas
      - 1 : une por columnas
      - None :  se obtiene un vector
      - out : permite guardar el resultado en un objeto existente

In [7]:
import numpy as np

# ------------ VECTORES ------------------------

arr_1 = np.concatenate(([1, 2, 3], [4, 5, 6]))
print(arr_1)

arr_2 = np.concatenate(([1, 2, 3], [4, 5, 6], [7, 8], [9]))
print(arr_2)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [22]:
import numpy as np

# ------------ MATRICES ------------------------

mat_1 = np.array([[1, 2, 3], [4, 5, 6]])   # matriz 2x3
mat_2 = np.array([[1, 1, 1], [2, 2, 2]])   # matriz 2x3

# Concatenar por columnas (axis=1)

# axis=0 pega las matrices una debajo de la otra (filas).
result_0 = np.concatenate((mat_1, mat_2), axis=0)
# axis=1 pega las matrices una al lado de la otra (columnas).
result_1 = np.concatenate((mat_1, mat_2), axis=1)
# axis=None obtenemos un vector con las matrices
result_none = np.concatenate((mat_1, mat_2), axis=None)
# propiedad out para almacenar el resultado en un objeto ya existente
obj = np.zeros((4, 3))
np.concatenate((mat_1, mat_2), out=obj)

print(result_0)
print(result_1)
print(result_none)
print(obj)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3]
 [4 5 6]
 [1 1 1]
 [2 2 2]]
[[1 2 3 1 1 1]
 [4 5 6 2 2 2]]
[1 2 3 4 5 6 1 1 1 2 2 2]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 1. 1.]
 [2. 2. 2.]]


In [29]:
# Concatenar matrices con vectores: se debe convertir el vector en una matriz

vec = np.array([10, 11, 12])
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat_vec = np.concatenate((mat, [vec]))

print(mat_vec)

# Concatenar el vector como una columna

mat_vec_col = np.concatenate((mat, np.array([vec]).T), axis=1)
print(mat_vec_col)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


np.hstack y np.vstack son funciones de NumPy que te simplifican la vida cuando querés apilar arrays sin tener que pensar demasiado en los ejes (axis).

🔹 np.hstack → Horizontal Stack

Apila los arrays horizontalmente (uno al lado del otro, como si fueran columnas).
Internamente, equivale a np.concatenate(..., axis=1) si los arrays son 2D.

In [36]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

result = np.hstack((a, b))
print(result)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Apila los arrays verticalmente (uno abajo del otro, como si fueran filas).
Internamente, equivale a np.concatenate(..., axis=0) si los arrays son 2D.

In [37]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

result = np.vstack((a, b))
print(result)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
